from typing import Any, Dict, Optional

class YoutubeDL:
    def __init__(self, params: Optional[Dict[str, Any]] = None) -> None: ...
    def download(self, url_list: list[str]) -> Any: ...
    def extract_info(self, url: str, download: bool = True) -> Dict[str, Any]: ... 