from typing import Any, Optional, Union
from pathlib import Path

class VideoFileClip:
    def __init__(self, filename: Union[str, Path]) -> None: ...
    def subclip(self, start_time: Optional[float] = None, end_time: Optional[float] = None) -> 'VideoFileClip': ...
    def write_videofile(self, filename: Union[str, Path], **kwargs: Any) -> None: ...
    def close(self) -> None: ... 