from typing import Any, Optional

def input(filename: str, **kwargs: Any) -> Any: ...
def output(stream: Any, filename: str, **kwargs: Any) -> Any: ...
def trim(stream: Any, start: Optional[float] = None, end: Optional[float] = None) -> Any: ...
def run(stream: Any, overwrite_output: bool = False) -> None: ...

class Error(Exception): ... 